### ISSUE TITLE
Release for aarch64-apple-darwin contains ELF linux executable

### ISSUE THREAD

**Issue by salemgolemugoo** [fluentci-io/fluentci#55]
Downloaded the latest https://github.com/fluentci-io/fluentci/releases/download/v0.15.2/fluentci_v0.15.2_aarch64-apple-darwin.tar.gz release and it contains linux binaries.

```
tar xvf fluentci_v0.15.2_aarch64-apple-darwin.tar
file fluentci
```

```
fluentci: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped
```

**Comment by tsirysndr** [comment]
Hey @salemgolemugoo ,

Thank you for reporting this issue and providing detailed information.

It seems that there's a bug with the Deno compile command on Linux when using the `--target aarch64-apple-darwin` option. The command is incorrectly generating Linux binaries instead of MacOS binaries. We understand that on MacOS, the `--target` option works perfectly and generates binaries for both Mac and Linux.

We apologize for the inconvenience this has caused. Our team is currently investigating the issue to determine the cause and will work on a fix as soon as possible.

We'll keep you updated on our progress and will notify you once a fix is released.

**Comment by salemgolemugoo** [comment]
When I tried to compile it with exact same `deno compile -A --output fluentci --target aarch64-apple-darwin main.ts` (as in your pipeline) it works pretty good in ubuntu:latest and deno:latest

**Comment by tsirysndr** [comment]
it appears the issue is not related to Deno itself but rather to the Deno installation from pkgx

**Comment by tsirysndr** [comment]
https://github.com/pkgxdev/pantry/pull/6791
